[package]
name = "vki"
version = "0.1.0"
authors = ["Aaron Loucks <aloucks@cofront.net>"]
edition = "2018"

[dependencies]
ash = "0.29.0"
vk-mem = "0.1.7"
lazy_static = "1.3.0"
libc = "0.2.50"
parking_lot = "0.7.1"
bitflags = "1.0.4"
log = "0.4.6"
smallvec = "0.6"
#crossbeam = "0.7.1"
either = "1.5.2"
backtrace = "0.3.15"
# backtrace = { path = "../backtrace-rs" }
winapi = { version = "0.3.7", features = ["dbghelp", "processthreadsapi"] }

[features]
default = ["winit-eventloop-2"]
winit-eventloop-2 = []

[patch.crates-io]
# ash = { git = "https://github.com/MaikKlein/ash.git", rev = "61d1049" }
# vk-mem = { path = "../vk-mem-rs" }

[dev-dependencies]
pretty_env_logger = "0.3.0"
winit = { git = "https://github.com/rust-windowing/winit.git", rev = "674bf04" } # branch = "eventloop-2.0"
# winit = { path = "../winit" } # branch = "eventloop-2.0"
# winit = "0.19.1"
num-traits = "0.2.6"
cgmath = "0.17.0"
image = "0.21.1"
rand = "0.6.5"
minterpolate = "0.4.0"

gltf = { version  = "0.12", features = ["extras", "utils", "import"] }
gltf-json = { version  = "0.12" }

[profile.dev]
opt-level = 2
