max_width = 120
newline_style = "Unix"
use_field_init_shorthand = true
edition = "2018"

#struct_field_align_threshold = 25
#struct_lit_single_line = false

#binop_separator = "Back"
#unstable_features = true
#struct_field_align_threshold = 30